name: Build (release package)

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build and publish to package repository
        id: publish
        run: |
          npm install
          npx @dappnode/dappnodesdk publish patch \
            --provider "remote" \
            --upload_to "ipfs" \
            --verbose \
            --github_release | tee build.log

          echo "DNP (DAppNode Package) built and uploaded" >> $GITHUB_STEP_SUMMARY
          grep "ipfs" build.log >> $GITHUB_STEP_SUMMARY
          ipfs_hash=$(grep -oP 'Release hash : \K/ipfs/\w+' build.log)
          echo "ipfs_hash=$ipfs_hash" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEVELOPER_ADDRESS: "0x7305356ad936A06c4ea5DF45AD5E5C3ff9Db818E"

      - name: Send message to Zulip
        uses: zulip/github-actions-zulip/send-message@v1
        with:
          api-key: ${{ secrets.ZULIP_API_KEY }}
          email: ${{ secrets.ZULIP_EMAIL }}
          organization-url: "https://hopr.zulipchat.com"
          type: "stream"
          to: "Releases"
          topic: "main"
          content: |
            A new hoprd dAppNode package version is available.
            - IPFS Hash: ${{ steps.publish.outputs.ipfs_hash }}
            Access to your dAppNode and check for the updates